### ISSUE TITLE
Can't make the searchbar responsive

### ISSUE THREAD

**Issue by patriciachrysy** [patriciachrysy/embeding-videos-images-project#2]
Used CSS Grid to style the searchbar on "embeded images and videos" project, but it is not responsive at all.

**Comment by Kyle-Law** [comment]
Try moving the .searchbar class inside form tag

**Comment by nyatindopatrick** [comment]
Size the search input using percentage.

**Comment by patriciachrysy** [comment]
> Try moving the .searchbar class inside form tag

Thanks, it works !!

**Comment by patriciachrysy** [comment]
> Size the search input using percentage.

It works, but partially.
